version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: "helpinghands_db"
      POSTGRES_USER: "iitu"
      POSTGRES_PASSWORD: "iitu"
    volumes:
      - helpinghandsdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "iitu@iitu.kz"
      PGADMIN_DEFAULT_PASSWORD: "iitu"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  helpinghandsdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge